[versions]
agp = "9.3.1"
android-compileSdk = "36"
android-minSdk = "24"
kotlin = "2.4.10"
okio = "3.18.1"
vanniktechPublish = "0.37.0"

[libraries]
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

[plugins]
androidKmpLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktechPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechPublish" }
